port="8000"
host="localhost"
path="theyAreHere.mp4"
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
bash break.sh > /$path/dev/null 