port="8080"
host="10.12.1.1"
path=""
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
curl $host:$port/$path > /dev/null  &
bash break.sh > /$path/dev/null 